baseURL = "https://mad.andreasvikke.dk"
languageCode = "en-us"
title = "Vikkes Mad"
theme = "cookbook"
sectionPagesMenu = "main"

[params.front]
defaultAuthor = "Andreas Vikke" #Put in the default name of the author of the recipe
defaultImage = "/images/defaultImage.jpg" #default image that will be used for a recipe with no image
defaultImageHeight = 512 #default recipe image height
defaultImageWidth = 512 # default recipe image width


# If you have a logo image, add it here, else just text (as an image) will be added
# The default height/width are the recommended bulma size (112W X 28H), best to get your logo as close as possible to that
# The site will SCALE your image, but will not force a stretch, so you may need to stretch it in external tool before using.
[params.logo]
fileName = "/images/logo.svg"
#fileName = "images/logo-alt.png" #alt logo if you are interested
height =  50
width = 200

[params.favicon]
fileName = "/images/favicon.ico" #your favicon here if you wish to change it.


[menu]
  [[menu.main]]
    name = "Hjem"
    pre = "fas fa-home" #icon, change if you would prefer a different icon
    url = "/"
    weight = 1
  [[menu.main]]
    name = "Kategorier" # change to w/e you want, tags or categories works best
    pre = "fas fa-tags" #icon, change if you would prefer a different icon
    url = "/tags/"
    weight = 2
  [[menu.main]]
    name = "Drinks" # change to w/e you want, tags or categories works best
    pre = "fas fa-cocktail" #icon, change if you would prefer a different icon
    url = "https://drinks.andreasvikke.dk"
    weight = 3


# Print output just creates a special route for a print view
[outputs]
  home = ["HTML", "JSON"]
  page = ["HTML", "PRINT"]
  
# The settings for the print format
[outputFormats]
[outputFormats.printFormat]
  name = "print"
  mediaType = "text/html"
  baseName = "print"
  isPlainText = false
  rel = "print"
  isHTML = true
  noUgly = true
  permalinkable = true
  path = "print"
